services:
  frontend:
    build: ./frontend
    container_name: mp_frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./frontend/app:/usr/share/nginx/html

  backend:
    build: ./backend
    container_name: mp_backend
    depends_on:
      - db
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html

  db:
    image: mysql:8.0
    container_name: mp_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metaprint
      MYSQL_USER: metaprint
      MYSQL_PASSWORD: metaprint
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
